site_name: bioprocs
theme: 'readthedocs'
markdown_extensions:
    - markdown.extensions.admonition:
    - pymdownx.superfences:
        preserve_tabs: true
    - toc:
        baselevel: 2
pages:
    - 'Introduction': 'index.md'
    - 'Processes': 'processes.md'
    - 'Aggregations': 'aggregations.md'
    - 'Binaries': 'binaries.md'